name: test

on:
  issues:
  
jobs:
  on-issue-labeled:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Setting title
        uses: actions/github-script@v7
        id: vars
        with:
          script: |
            echo ${{ toJson(github.event.issue.title) }}
